export const Books=[
    {
        id:1,
        title:"Pride and Prejudice",
        author:"Jane Austen",
        published:"1893",
        pages:328,
        coverImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr39Gr590-Dq6VkSxjG-EZErLw8YCcy_zoPg&s",
        description:"Pride and Prejudice is the second novel by English author Jane Austen, published in 1813. A novel of manners, it follows the character development of Elizabeth Bennet, the protagonist of the book, who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.",
    },
    {
        id:2,
        title:"1984",
        author:"F.Scott Fitzgerald",
        published:"1949",
        pages:328,
        coverImage:"https://ashokbookcentre.com/wp-content/uploads/2023/08/514CVwOrybL.jpg",
        description:"Nineteen Eighty-Four (also published as 1984) is a dystopian novel and cautionary tale by English writer George Orwell. It was published on 8 June 1949 by Secker & Warburg as Orwell's ninth and final book completed in his lifetime. Thematically, it centres on the consequences of totalitarianism, mass surveillance, and repressive regimentation of people and behaviours within society.[3][4] Orwell, a staunch believer.",
    },
    {
        id:3,
        title:"War and Peace",
        author:"Leo Tolstoy",
        published:"1869",
        pages:316,
        coverImage:"https://images.squarespace-cdn.com/content/v1/5a44280432601e14c4a69783/1557411103181-HL3N63QX4F3AGFV5BUR8/War%2Band%2BPeace%2BCover",
        description:"The book chronicles the French invasion of Russia and its aftermath during the Napoleonic era. It uses five interlocking narratives following different Russian aristocratic families to illustrate Napoleon's impact on Tsarist society. Portions of an earlier version, titled The Year 1805,[4] were serialized in The Russian Messenger from 1865 to 1867 before the novel was published in its entirety in 1869.[5]",
    },
    {
        id:4,
        title:"Beloved",
        author:"Toni Morrison",
        published:"1987",
        coverImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFOFgtTLves8d65a1K_UTZK26TqQ5xKx1q9Q&s",
        description:"Beloved is a 1987 novel by American novelist Toni Morrison. Set in the period after the American Civil War, the novel tells the story of a dysfunctional family of formerly enslaved people whose Cincinnati home is haunted by a malevolent spirit. The narrative of Beloved derives from the life of Margaret Garner, an enslaved person in the slave state of Kentucky who escaped and fled to the free state of Ohio ",
    },
    {
        id:5,
        title:"Great Expectations",
        author:"Charles Dickens",
        published:"1861",
        pages:256,
        coverImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1i0JRSUA2CPfYI-CkYWjPNImel2z6qiYgpQ&s",
        description:"Great Expectations is the thirteenth novel by English author Charles Dickens and his penultimate completed novel. The novel is a Bildungsroman and depicts the education of an orphan nicknamed Pip. It is Dickens' second novel, after David Copperfield, to be fully narrated in the first person.[N 1] The novel was first published as a serial in Dickens's weekly periodical All the Year Round, from 1 December 1860 to August 1861.[1] In October 1861, Chapman & Hall published the novel in three volumes.[2][3][4]",
    },
    {
        id:6,
        title:"To kill a Mockingbird",
        author:"Harper Lee",
        published:"1960",
        pages:398,
        coverImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNoo1jB9pRISmn7a31BhToLPvgwmL8lAJZRg&s",
        description:"To Kill a Mockingbird is a novel by the American author Harper Lee. It was published in July 1960 and became instantly successful. In the United States, it is widely read in high schools and middle schools. To Kill a Mockingbird has become a classic of modern American literature; a year after its release, it won the Pulitzer Prize. The plot and characters are loosely based on Lee's observations of her family, her neighbors and an event that occurred near her hometown of Monroeville, Alabama, in 1936, when she was ten.",
    },
    {
        id:7,
        title:"Adeventures of Huckleberry Finn",
        author:"Mark Twain",
        published:"1884",
        pages:421,
        coverImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIIyel4yDlE2XRqhR_ptX2ayJls5waKS9sUg&s",
        description:"Adventures of Huckleberry Finn is a novel by American author Mark Twain that was first published in the United Kingdom in December 1884 and in the United States in February 1885.Commonly named among the Great American Novels, the work is among the first in major American literature to be written throughout in vernacular English, characterized by local color regionalism. It is told in the first person by Huckleberry .Huck Finn, the narrator of two other Twain novels (Tom Sawyer Abroad and Tom Sawyer, Detective) and a friend",
    },
    {
        id:8,
        title:"The Catcher in the Eye",
        author:"J.D.Salinger",
        published:"1945",
        pages:352,
        coverImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4LTIvo1W_g0QCkxPtOVydS1bXKqR7NPNLbw&s",
        description:"The Catcher in the Rye is a novel by American author J. D. Salinger that was partially published in serial form in 1945–46 before being novelized in 1951. Originally intended for adults, it is often read by adolescents for its themes of angst and alienation, and as a critique of superficiality in society.[4][5] The novel also deals with themes of innocence, identity, belonging, loss, connection, sex, and depression. The main character, Holden Caulfield, has become an icon for teenage rebellion.[6] Caulfield, nearly of age.",
    },
    {
        id:9,
        title:"In Search of Lost time",
        author:"Marcel Proust",
        published:"1992",
        pages:4215,
        coverImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtJ1PuVAT0Z0YXUZf1KS6kAmcClTbffOtFNg&s",
        description:"n Search of Lost Time (French: À la recherche du temps perdu), first translated into English as Remembrance of Things Past, and sometimes referred to in French as La Recherche (The Search), is a novel in seven volumes by French author Marcel Proust. This early 20th-century work is his most prominent, known both for its length and its theme of involuntary memory. The most famous example of the story and is beautifully written which is very useful in real life and people can be conscious of applications",
    },
    {
        id:10,
        title:"The Lord of Rings",
        author:"J.R.R.Tolkein",
        published:"1937",
        pages:1077,
        coverImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9GK7zXBR-r5p0BjhvnC2VN6kumJxC1Ab_qw&s",
        description:"The Lord of the Rings is an epic[1] high fantasy novel[a] by the English author and scholar J. R. R. Tolkien. Set in Middle-earth, the story began as a sequel to Tolkien's 1937 children's book The Hobbit, but eventually developed into a much larger work. Written in stages between 1937 and 1949, The Lord of the Rings is one of the best-selling books ever written, with over 150 million copies sold.[2]",
    },
]